BENCHMARK: longest6
route_rel: scripts/leaderboard/routes/longest6_pt1.xml
routes: ${user.working_dir}/${eval.route_rel}
scenarios_rel: leaderboard/data/longest6/eval_scenarios.json
scenarios: ${user.plant_dir}/${eval.scenarios_rel}
